// src/integrity_data.rs
// src/integrity_data.rs
// This file is auto-generated by build.rs.
// Do not edit manually.

/// The expected HMAC-SHA-256 tag of the code segment.
/// This is a placeholder. The actual value will be injected post-build.
/// Pattern: "__PQC_NOSTD_HMAC_PLACEHOLDER__" (30 bytes) + 0x00, 0x00
#[used]
pub static EXPECTED_HMAC: [u8; 32] = *b"__PQC_NOSTD_HMAC_PLACEHOLDER__\x00\x00";
